{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "<class 'PIL.PngImagePlugin.PngImageFile'>\n",
      "(1, 30, 30, 4)\n",
      "<class 'numpy.ndarray'>\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-7-3e160a2dc0ba>\", line 90, in <lambda>\n",
      "    classify_b=Button(top,text=\"Classier l'image\",command=lambda: classify(file_path),padx=10,pady=5)\n",
      "  File \"<ipython-input-7-3e160a2dc0ba>\", line 83, in classify\n",
      "    pred = model.predict_classes([image])[0]\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\util\\deprecation.py\", line 324, in new_func\n",
      "    return func(*args, **kwargs)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\sequential.py\", line 453, in predict_classes\n",
      "    proba = self.predict(x, batch_size=batch_size, verbose=verbose)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\training.py\", line 130, in _method_wrapper\n",
      "    return method(self, *args, **kwargs)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\training.py\", line 1599, in predict\n",
      "    tmp_batch_outputs = predict_function(iterator)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 780, in __call__\n",
      "    result = self._call(*args, **kwds)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 823, in _call\n",
      "    self._initialize(args, kwds, add_initializers_to=initializers)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 696, in _initialize\n",
      "    self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 2855, in _get_concrete_function_internal_garbage_collected\n",
      "    graph_function, _, _ = self._maybe_define_function(args, kwargs)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3213, in _maybe_define_function\n",
      "    graph_function = self._create_graph_function(args, kwargs)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3065, in _create_graph_function\n",
      "    func_graph_module.func_graph_from_py_func(\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 986, in func_graph_from_py_func\n",
      "    func_outputs = python_func(*func_args, **func_kwargs)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 600, in wrapped_fn\n",
      "    return weak_wrapped_fn().__wrapped__(*args, **kwds)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 973, in wrapper\n",
      "    raise e.ag_error_metadata.to_exception(e)\n",
      "ValueError: in user code:\n",
      "\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\training.py:1462 predict_function  *\n",
      "        return step_function(self, iterator)\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\training.py:1452 step_function  **\n",
      "        outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:1211 run\n",
      "        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:2585 call_for_each_replica\n",
      "        return self._call_for_each_replica(fn, args, kwargs)\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:2945 _call_for_each_replica\n",
      "        return fn(*args, **kwargs)\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\training.py:1445 run_step  **\n",
      "        outputs = model.predict_step(data)\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\training.py:1418 predict_step\n",
      "        return self(x, training=False)\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\base_layer.py:975 __call__\n",
      "        input_spec.assert_input_compatibility(self.input_spec, inputs,\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\input_spec.py:212 assert_input_compatibility\n",
      "        raise ValueError(\n",
      "\n",
      "    ValueError: Input 0 of layer sequential_1 is incompatible with the layer: expected axis -1 of input shape to have value 3 but received input with shape [None, 30, 30, 4]\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "(1, 30, 30, 4)\n",
      "<class 'numpy.ndarray'>\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-7-3e160a2dc0ba>\", line 90, in <lambda>\n",
      "    classify_b=Button(top,text=\"Classier l'image\",command=lambda: classify(file_path),padx=10,pady=5)\n",
      "  File \"<ipython-input-7-3e160a2dc0ba>\", line 83, in classify\n",
      "    pred = model.predict_classes([image])[0]\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\util\\deprecation.py\", line 324, in new_func\n",
      "    return func(*args, **kwargs)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\sequential.py\", line 453, in predict_classes\n",
      "    proba = self.predict(x, batch_size=batch_size, verbose=verbose)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\training.py\", line 130, in _method_wrapper\n",
      "    return method(self, *args, **kwargs)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\training.py\", line 1599, in predict\n",
      "    tmp_batch_outputs = predict_function(iterator)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 780, in __call__\n",
      "    result = self._call(*args, **kwds)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 814, in _call\n",
      "    results = self._stateful_fn(*args, **kwds)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 2828, in __call__\n",
      "    graph_function, args, kwargs = self._maybe_define_function(args, kwargs)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3210, in _maybe_define_function\n",
      "    return self._define_function_with_shape_relaxation(args, kwargs)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3141, in _define_function_with_shape_relaxation\n",
      "    graph_function = self._create_graph_function(\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3065, in _create_graph_function\n",
      "    func_graph_module.func_graph_from_py_func(\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 986, in func_graph_from_py_func\n",
      "    func_outputs = python_func(*func_args, **func_kwargs)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 600, in wrapped_fn\n",
      "    return weak_wrapped_fn().__wrapped__(*args, **kwds)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 973, in wrapper\n",
      "    raise e.ag_error_metadata.to_exception(e)\n",
      "ValueError: in user code:\n",
      "\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\training.py:1462 predict_function  *\n",
      "        return step_function(self, iterator)\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\training.py:1452 step_function  **\n",
      "        outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:1211 run\n",
      "        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:2585 call_for_each_replica\n",
      "        return self._call_for_each_replica(fn, args, kwargs)\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:2945 _call_for_each_replica\n",
      "        return fn(*args, **kwargs)\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\training.py:1445 run_step  **\n",
      "        outputs = model.predict_step(data)\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\training.py:1418 predict_step\n",
      "        return self(x, training=False)\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\base_layer.py:975 __call__\n",
      "        input_spec.assert_input_compatibility(self.input_spec, inputs,\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\input_spec.py:212 assert_input_compatibility\n",
      "        raise ValueError(\n",
      "\n",
      "    ValueError: Input 0 of layer sequential_1 is incompatible with the layer: expected axis -1 of input shape to have value 3 but received input with shape [None, 30, 30, 4]\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "(1, 30, 30, 4)\n",
      "<class 'numpy.ndarray'>\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-7-3e160a2dc0ba>\", line 90, in <lambda>\n",
      "    classify_b=Button(top,text=\"Classier l'image\",command=lambda: classify(file_path),padx=10,pady=5)\n",
      "  File \"<ipython-input-7-3e160a2dc0ba>\", line 83, in classify\n",
      "    pred = model.predict_classes([image])[0]\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\util\\deprecation.py\", line 324, in new_func\n",
      "    return func(*args, **kwargs)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\sequential.py\", line 453, in predict_classes\n",
      "    proba = self.predict(x, batch_size=batch_size, verbose=verbose)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\training.py\", line 130, in _method_wrapper\n",
      "    return method(self, *args, **kwargs)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\training.py\", line 1599, in predict\n",
      "    tmp_batch_outputs = predict_function(iterator)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 780, in __call__\n",
      "    result = self._call(*args, **kwds)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 814, in _call\n",
      "    results = self._stateful_fn(*args, **kwds)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 2828, in __call__\n",
      "    graph_function, args, kwargs = self._maybe_define_function(args, kwargs)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3210, in _maybe_define_function\n",
      "    return self._define_function_with_shape_relaxation(args, kwargs)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3141, in _define_function_with_shape_relaxation\n",
      "    graph_function = self._create_graph_function(\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3065, in _create_graph_function\n",
      "    func_graph_module.func_graph_from_py_func(\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 986, in func_graph_from_py_func\n",
      "    func_outputs = python_func(*func_args, **func_kwargs)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 600, in wrapped_fn\n",
      "    return weak_wrapped_fn().__wrapped__(*args, **kwds)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 973, in wrapper\n",
      "    raise e.ag_error_metadata.to_exception(e)\n",
      "ValueError: in user code:\n",
      "\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\training.py:1462 predict_function  *\n",
      "        return step_function(self, iterator)\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\training.py:1452 step_function  **\n",
      "        outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:1211 run\n",
      "        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:2585 call_for_each_replica\n",
      "        return self._call_for_each_replica(fn, args, kwargs)\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:2945 _call_for_each_replica\n",
      "        return fn(*args, **kwargs)\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\training.py:1445 run_step  **\n",
      "        outputs = model.predict_step(data)\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\training.py:1418 predict_step\n",
      "        return self(x, training=False)\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\base_layer.py:975 __call__\n",
      "        input_spec.assert_input_compatibility(self.input_spec, inputs,\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\input_spec.py:212 assert_input_compatibility\n",
      "        raise ValueError(\n",
      "\n",
      "    ValueError: Input 0 of layer sequential_1 is incompatible with the layer: expected axis -1 of input shape to have value 3 but received input with shape [None, 30, 30, 4]\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "(1, 30, 30, 4)\n",
      "<class 'numpy.ndarray'>\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-7-3e160a2dc0ba>\", line 90, in <lambda>\n",
      "    classify_b=Button(top,text=\"Classier l'image\",command=lambda: classify(file_path),padx=10,pady=5)\n",
      "  File \"<ipython-input-7-3e160a2dc0ba>\", line 83, in classify\n",
      "    pred = model.predict_classes([image])[0]\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\util\\deprecation.py\", line 324, in new_func\n",
      "    return func(*args, **kwargs)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\sequential.py\", line 453, in predict_classes\n",
      "    proba = self.predict(x, batch_size=batch_size, verbose=verbose)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\training.py\", line 130, in _method_wrapper\n",
      "    return method(self, *args, **kwargs)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\training.py\", line 1599, in predict\n",
      "    tmp_batch_outputs = predict_function(iterator)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 780, in __call__\n",
      "    result = self._call(*args, **kwds)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 814, in _call\n",
      "    results = self._stateful_fn(*args, **kwds)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 2828, in __call__\n",
      "    graph_function, args, kwargs = self._maybe_define_function(args, kwargs)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3210, in _maybe_define_function\n",
      "    return self._define_function_with_shape_relaxation(args, kwargs)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3141, in _define_function_with_shape_relaxation\n",
      "    graph_function = self._create_graph_function(\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3065, in _create_graph_function\n",
      "    func_graph_module.func_graph_from_py_func(\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 986, in func_graph_from_py_func\n",
      "    func_outputs = python_func(*func_args, **func_kwargs)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 600, in wrapped_fn\n",
      "    return weak_wrapped_fn().__wrapped__(*args, **kwds)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 973, in wrapper\n",
      "    raise e.ag_error_metadata.to_exception(e)\n",
      "ValueError: in user code:\n",
      "\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\training.py:1462 predict_function  *\n",
      "        return step_function(self, iterator)\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\training.py:1452 step_function  **\n",
      "        outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:1211 run\n",
      "        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:2585 call_for_each_replica\n",
      "        return self._call_for_each_replica(fn, args, kwargs)\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:2945 _call_for_each_replica\n",
      "        return fn(*args, **kwargs)\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\training.py:1445 run_step  **\n",
      "        outputs = model.predict_step(data)\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\training.py:1418 predict_step\n",
      "        return self(x, training=False)\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\base_layer.py:975 __call__\n",
      "        input_spec.assert_input_compatibility(self.input_spec, inputs,\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\input_spec.py:212 assert_input_compatibility\n",
      "        raise ValueError(\n",
      "\n",
      "    ValueError: Input 0 of layer sequential_1 is incompatible with the layer: expected axis -1 of input shape to have value 3 but received input with shape [None, 30, 30, 4]\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "(1, 30, 30, 4)\n",
      "<class 'numpy.ndarray'>\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-7-3e160a2dc0ba>\", line 90, in <lambda>\n",
      "    classify_b=Button(top,text=\"Classier l'image\",command=lambda: classify(file_path),padx=10,pady=5)\n",
      "  File \"<ipython-input-7-3e160a2dc0ba>\", line 83, in classify\n",
      "    pred = model.predict_classes([image])[0]\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\util\\deprecation.py\", line 324, in new_func\n",
      "    return func(*args, **kwargs)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\sequential.py\", line 453, in predict_classes\n",
      "    proba = self.predict(x, batch_size=batch_size, verbose=verbose)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\training.py\", line 130, in _method_wrapper\n",
      "    return method(self, *args, **kwargs)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\training.py\", line 1599, in predict\n",
      "    tmp_batch_outputs = predict_function(iterator)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 780, in __call__\n",
      "    result = self._call(*args, **kwds)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 814, in _call\n",
      "    results = self._stateful_fn(*args, **kwds)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 2828, in __call__\n",
      "    graph_function, args, kwargs = self._maybe_define_function(args, kwargs)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3210, in _maybe_define_function\n",
      "    return self._define_function_with_shape_relaxation(args, kwargs)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3141, in _define_function_with_shape_relaxation\n",
      "    graph_function = self._create_graph_function(\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3065, in _create_graph_function\n",
      "    func_graph_module.func_graph_from_py_func(\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 986, in func_graph_from_py_func\n",
      "    func_outputs = python_func(*func_args, **func_kwargs)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 600, in wrapped_fn\n",
      "    return weak_wrapped_fn().__wrapped__(*args, **kwds)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 973, in wrapper\n",
      "    raise e.ag_error_metadata.to_exception(e)\n",
      "ValueError: in user code:\n",
      "\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\training.py:1462 predict_function  *\n",
      "        return step_function(self, iterator)\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\training.py:1452 step_function  **\n",
      "        outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:1211 run\n",
      "        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:2585 call_for_each_replica\n",
      "        return self._call_for_each_replica(fn, args, kwargs)\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:2945 _call_for_each_replica\n",
      "        return fn(*args, **kwargs)\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\training.py:1445 run_step  **\n",
      "        outputs = model.predict_step(data)\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\training.py:1418 predict_step\n",
      "        return self(x, training=False)\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\base_layer.py:975 __call__\n",
      "        input_spec.assert_input_compatibility(self.input_spec, inputs,\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\input_spec.py:212 assert_input_compatibility\n",
      "        raise ValueError(\n",
      "\n",
      "    ValueError: Input 0 of layer sequential_1 is incompatible with the layer: expected axis -1 of input shape to have value 3 but received input with shape [None, 30, 30, 4]\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "(1, 30, 30, 4)\n",
      "<class 'numpy.ndarray'>\n",
      "(1, 30, 30, 4)\n",
      "<class 'numpy.ndarray'>\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-7-3e160a2dc0ba>\", line 90, in <lambda>\n",
      "    classify_b=Button(top,text=\"Classier l'image\",command=lambda: classify(file_path),padx=10,pady=5)\n",
      "  File \"<ipython-input-7-3e160a2dc0ba>\", line 83, in classify\n",
      "    pred = model.predict_classes([image])[0]\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\util\\deprecation.py\", line 324, in new_func\n",
      "    return func(*args, **kwargs)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\sequential.py\", line 453, in predict_classes\n",
      "    proba = self.predict(x, batch_size=batch_size, verbose=verbose)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\training.py\", line 130, in _method_wrapper\n",
      "    return method(self, *args, **kwargs)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\training.py\", line 1599, in predict\n",
      "    tmp_batch_outputs = predict_function(iterator)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 780, in __call__\n",
      "    result = self._call(*args, **kwds)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 814, in _call\n",
      "    results = self._stateful_fn(*args, **kwds)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 2828, in __call__\n",
      "    graph_function, args, kwargs = self._maybe_define_function(args, kwargs)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3210, in _maybe_define_function\n",
      "    return self._define_function_with_shape_relaxation(args, kwargs)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3141, in _define_function_with_shape_relaxation\n",
      "    graph_function = self._create_graph_function(\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3065, in _create_graph_function\n",
      "    func_graph_module.func_graph_from_py_func(\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 986, in func_graph_from_py_func\n",
      "    func_outputs = python_func(*func_args, **func_kwargs)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 600, in wrapped_fn\n",
      "    return weak_wrapped_fn().__wrapped__(*args, **kwds)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 973, in wrapper\n",
      "    raise e.ag_error_metadata.to_exception(e)\n",
      "ValueError: in user code:\n",
      "\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\training.py:1462 predict_function  *\n",
      "        return step_function(self, iterator)\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\training.py:1452 step_function  **\n",
      "        outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:1211 run\n",
      "        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:2585 call_for_each_replica\n",
      "        return self._call_for_each_replica(fn, args, kwargs)\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:2945 _call_for_each_replica\n",
      "        return fn(*args, **kwargs)\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\training.py:1445 run_step  **\n",
      "        outputs = model.predict_step(data)\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\training.py:1418 predict_step\n",
      "        return self(x, training=False)\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\base_layer.py:975 __call__\n",
      "        input_spec.assert_input_compatibility(self.input_spec, inputs,\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\input_spec.py:212 assert_input_compatibility\n",
      "        raise ValueError(\n",
      "\n",
      "    ValueError: Input 0 of layer sequential_1 is incompatible with the layer: expected axis -1 of input shape to have value 3 but received input with shape [None, 30, 30, 4]\n",
      "\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-7-3e160a2dc0ba>\", line 90, in <lambda>\n",
      "    classify_b=Button(top,text=\"Classier l'image\",command=lambda: classify(file_path),padx=10,pady=5)\n",
      "  File \"<ipython-input-7-3e160a2dc0ba>\", line 83, in classify\n",
      "    pred = model.predict_classes([image])[0]\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\util\\deprecation.py\", line 324, in new_func\n",
      "    return func(*args, **kwargs)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\sequential.py\", line 453, in predict_classes\n",
      "    proba = self.predict(x, batch_size=batch_size, verbose=verbose)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\training.py\", line 130, in _method_wrapper\n",
      "    return method(self, *args, **kwargs)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\training.py\", line 1599, in predict\n",
      "    tmp_batch_outputs = predict_function(iterator)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 780, in __call__\n",
      "    result = self._call(*args, **kwds)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 814, in _call\n",
      "    results = self._stateful_fn(*args, **kwds)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 2828, in __call__\n",
      "    graph_function, args, kwargs = self._maybe_define_function(args, kwargs)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3210, in _maybe_define_function\n",
      "    return self._define_function_with_shape_relaxation(args, kwargs)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3141, in _define_function_with_shape_relaxation\n",
      "    graph_function = self._create_graph_function(\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3065, in _create_graph_function\n",
      "    func_graph_module.func_graph_from_py_func(\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 986, in func_graph_from_py_func\n",
      "    func_outputs = python_func(*func_args, **func_kwargs)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 600, in wrapped_fn\n",
      "    return weak_wrapped_fn().__wrapped__(*args, **kwds)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 973, in wrapper\n",
      "    raise e.ag_error_metadata.to_exception(e)\n",
      "ValueError: in user code:\n",
      "\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\training.py:1462 predict_function  *\n",
      "        return step_function(self, iterator)\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\training.py:1452 step_function  **\n",
      "        outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:1211 run\n",
      "        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:2585 call_for_each_replica\n",
      "        return self._call_for_each_replica(fn, args, kwargs)\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:2945 _call_for_each_replica\n",
      "        return fn(*args, **kwargs)\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\training.py:1445 run_step  **\n",
      "        outputs = model.predict_step(data)\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\training.py:1418 predict_step\n",
      "        return self(x, training=False)\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\base_layer.py:975 __call__\n",
      "        input_spec.assert_input_compatibility(self.input_spec, inputs,\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\input_spec.py:212 assert_input_compatibility\n",
      "        raise ValueError(\n",
      "\n",
      "    ValueError: Input 0 of layer sequential_1 is incompatible with the layer: expected axis -1 of input shape to have value 3 but received input with shape [None, 30, 30, 4]\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "(1, 30, 30, 4)\n",
      "<class 'numpy.ndarray'>\n",
      "(1, 30, 30, 4)\n",
      "<class 'numpy.ndarray'>\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-7-3e160a2dc0ba>\", line 90, in <lambda>\n",
      "    classify_b=Button(top,text=\"Classier l'image\",command=lambda: classify(file_path),padx=10,pady=5)\n",
      "  File \"<ipython-input-7-3e160a2dc0ba>\", line 83, in classify\n",
      "    pred = model.predict_classes([image])[0]\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\util\\deprecation.py\", line 324, in new_func\n",
      "    return func(*args, **kwargs)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\sequential.py\", line 453, in predict_classes\n",
      "    proba = self.predict(x, batch_size=batch_size, verbose=verbose)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\training.py\", line 130, in _method_wrapper\n",
      "    return method(self, *args, **kwargs)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\training.py\", line 1599, in predict\n",
      "    tmp_batch_outputs = predict_function(iterator)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 780, in __call__\n",
      "    result = self._call(*args, **kwds)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 814, in _call\n",
      "    results = self._stateful_fn(*args, **kwds)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 2828, in __call__\n",
      "    graph_function, args, kwargs = self._maybe_define_function(args, kwargs)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3210, in _maybe_define_function\n",
      "    return self._define_function_with_shape_relaxation(args, kwargs)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3141, in _define_function_with_shape_relaxation\n",
      "    graph_function = self._create_graph_function(\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3065, in _create_graph_function\n",
      "    func_graph_module.func_graph_from_py_func(\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 986, in func_graph_from_py_func\n",
      "    func_outputs = python_func(*func_args, **func_kwargs)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 600, in wrapped_fn\n",
      "    return weak_wrapped_fn().__wrapped__(*args, **kwds)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 973, in wrapper\n",
      "    raise e.ag_error_metadata.to_exception(e)\n",
      "ValueError: in user code:\n",
      "\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\training.py:1462 predict_function  *\n",
      "        return step_function(self, iterator)\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\training.py:1452 step_function  **\n",
      "        outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:1211 run\n",
      "        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:2585 call_for_each_replica\n",
      "        return self._call_for_each_replica(fn, args, kwargs)\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:2945 _call_for_each_replica\n",
      "        return fn(*args, **kwargs)\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\training.py:1445 run_step  **\n",
      "        outputs = model.predict_step(data)\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\training.py:1418 predict_step\n",
      "        return self(x, training=False)\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\base_layer.py:975 __call__\n",
      "        input_spec.assert_input_compatibility(self.input_spec, inputs,\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\input_spec.py:212 assert_input_compatibility\n",
      "        raise ValueError(\n",
      "\n",
      "    ValueError: Input 0 of layer sequential_1 is incompatible with the layer: expected axis -1 of input shape to have value 3 but received input with shape [None, 30, 30, 4]\n",
      "\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-7-3e160a2dc0ba>\", line 90, in <lambda>\n",
      "    classify_b=Button(top,text=\"Classier l'image\",command=lambda: classify(file_path),padx=10,pady=5)\n",
      "  File \"<ipython-input-7-3e160a2dc0ba>\", line 83, in classify\n",
      "    pred = model.predict_classes([image])[0]\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\util\\deprecation.py\", line 324, in new_func\n",
      "    return func(*args, **kwargs)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\sequential.py\", line 453, in predict_classes\n",
      "    proba = self.predict(x, batch_size=batch_size, verbose=verbose)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\training.py\", line 130, in _method_wrapper\n",
      "    return method(self, *args, **kwargs)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\training.py\", line 1599, in predict\n",
      "    tmp_batch_outputs = predict_function(iterator)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 780, in __call__\n",
      "    result = self._call(*args, **kwds)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 814, in _call\n",
      "    results = self._stateful_fn(*args, **kwds)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 2828, in __call__\n",
      "    graph_function, args, kwargs = self._maybe_define_function(args, kwargs)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3210, in _maybe_define_function\n",
      "    return self._define_function_with_shape_relaxation(args, kwargs)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3141, in _define_function_with_shape_relaxation\n",
      "    graph_function = self._create_graph_function(\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3065, in _create_graph_function\n",
      "    func_graph_module.func_graph_from_py_func(\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 986, in func_graph_from_py_func\n",
      "    func_outputs = python_func(*func_args, **func_kwargs)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 600, in wrapped_fn\n",
      "    return weak_wrapped_fn().__wrapped__(*args, **kwds)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 973, in wrapper\n",
      "    raise e.ag_error_metadata.to_exception(e)\n",
      "ValueError: in user code:\n",
      "\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\training.py:1462 predict_function  *\n",
      "        return step_function(self, iterator)\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\training.py:1452 step_function  **\n",
      "        outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:1211 run\n",
      "        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:2585 call_for_each_replica\n",
      "        return self._call_for_each_replica(fn, args, kwargs)\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:2945 _call_for_each_replica\n",
      "        return fn(*args, **kwargs)\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\training.py:1445 run_step  **\n",
      "        outputs = model.predict_step(data)\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\training.py:1418 predict_step\n",
      "        return self(x, training=False)\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\base_layer.py:975 __call__\n",
      "        input_spec.assert_input_compatibility(self.input_spec, inputs,\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\input_spec.py:212 assert_input_compatibility\n",
      "        raise ValueError(\n",
      "\n",
      "    ValueError: Input 0 of layer sequential_1 is incompatible with the layer: expected axis -1 of input shape to have value 3 but received input with shape [None, 30, 30, 4]\n",
      "\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-7-3e160a2dc0ba>\", line 90, in <lambda>\n",
      "    classify_b=Button(top,text=\"Classier l'image\",command=lambda: classify(file_path),padx=10,pady=5)\n",
      "  File \"<ipython-input-7-3e160a2dc0ba>\", line 83, in classify\n",
      "    pred = model.predict_classes([image])[0]\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\util\\deprecation.py\", line 324, in new_func\n",
      "    return func(*args, **kwargs)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\sequential.py\", line 453, in predict_classes\n",
      "    proba = self.predict(x, batch_size=batch_size, verbose=verbose)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\training.py\", line 130, in _method_wrapper\n",
      "    return method(self, *args, **kwargs)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\training.py\", line 1599, in predict\n",
      "    tmp_batch_outputs = predict_function(iterator)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 780, in __call__\n",
      "    result = self._call(*args, **kwds)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 814, in _call\n",
      "    results = self._stateful_fn(*args, **kwds)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 2828, in __call__\n",
      "    graph_function, args, kwargs = self._maybe_define_function(args, kwargs)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3210, in _maybe_define_function\n",
      "    return self._define_function_with_shape_relaxation(args, kwargs)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3141, in _define_function_with_shape_relaxation\n",
      "    graph_function = self._create_graph_function(\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3065, in _create_graph_function\n",
      "    func_graph_module.func_graph_from_py_func(\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 986, in func_graph_from_py_func\n",
      "    func_outputs = python_func(*func_args, **func_kwargs)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 600, in wrapped_fn\n",
      "    return weak_wrapped_fn().__wrapped__(*args, **kwds)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 973, in wrapper\n",
      "    raise e.ag_error_metadata.to_exception(e)\n",
      "ValueError: in user code:\n",
      "\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\training.py:1462 predict_function  *\n",
      "        return step_function(self, iterator)\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\training.py:1452 step_function  **\n",
      "        outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:1211 run\n",
      "        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:2585 call_for_each_replica\n",
      "        return self._call_for_each_replica(fn, args, kwargs)\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:2945 _call_for_each_replica\n",
      "        return fn(*args, **kwargs)\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\training.py:1445 run_step  **\n",
      "        outputs = model.predict_step(data)\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\training.py:1418 predict_step\n",
      "        return self(x, training=False)\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\base_layer.py:975 __call__\n",
      "        input_spec.assert_input_compatibility(self.input_spec, inputs,\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\input_spec.py:212 assert_input_compatibility\n",
      "        raise ValueError(\n",
      "\n",
      "    ValueError: Input 0 of layer sequential_1 is incompatible with the layer: expected axis -1 of input shape to have value 3 but received input with shape [None, 30, 30, 4]\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "(1, 30, 30, 4)\n",
      "<class 'numpy.ndarray'>\n",
      "(1, 30, 30, 4)\n",
      "<class 'numpy.ndarray'>\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-7-3e160a2dc0ba>\", line 90, in <lambda>\n",
      "    classify_b=Button(top,text=\"Classier l'image\",command=lambda: classify(file_path),padx=10,pady=5)\n",
      "  File \"<ipython-input-7-3e160a2dc0ba>\", line 83, in classify\n",
      "    pred = model.predict_classes([image])[0]\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\util\\deprecation.py\", line 324, in new_func\n",
      "    return func(*args, **kwargs)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\sequential.py\", line 453, in predict_classes\n",
      "    proba = self.predict(x, batch_size=batch_size, verbose=verbose)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\training.py\", line 130, in _method_wrapper\n",
      "    return method(self, *args, **kwargs)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\training.py\", line 1599, in predict\n",
      "    tmp_batch_outputs = predict_function(iterator)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 780, in __call__\n",
      "    result = self._call(*args, **kwds)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 814, in _call\n",
      "    results = self._stateful_fn(*args, **kwds)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 2828, in __call__\n",
      "    graph_function, args, kwargs = self._maybe_define_function(args, kwargs)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3210, in _maybe_define_function\n",
      "    return self._define_function_with_shape_relaxation(args, kwargs)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3141, in _define_function_with_shape_relaxation\n",
      "    graph_function = self._create_graph_function(\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3065, in _create_graph_function\n",
      "    func_graph_module.func_graph_from_py_func(\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 986, in func_graph_from_py_func\n",
      "    func_outputs = python_func(*func_args, **func_kwargs)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 600, in wrapped_fn\n",
      "    return weak_wrapped_fn().__wrapped__(*args, **kwds)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 973, in wrapper\n",
      "    raise e.ag_error_metadata.to_exception(e)\n",
      "ValueError: in user code:\n",
      "\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\training.py:1462 predict_function  *\n",
      "        return step_function(self, iterator)\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\training.py:1452 step_function  **\n",
      "        outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:1211 run\n",
      "        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:2585 call_for_each_replica\n",
      "        return self._call_for_each_replica(fn, args, kwargs)\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:2945 _call_for_each_replica\n",
      "        return fn(*args, **kwargs)\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\training.py:1445 run_step  **\n",
      "        outputs = model.predict_step(data)\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\training.py:1418 predict_step\n",
      "        return self(x, training=False)\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\base_layer.py:975 __call__\n",
      "        input_spec.assert_input_compatibility(self.input_spec, inputs,\n",
      "    c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\input_spec.py:212 assert_input_compatibility\n",
      "        raise ValueError(\n",
      "\n",
      "    ValueError: Input 0 of layer sequential_1 is incompatible with the layer: expected axis -1 of input shape to have value 3 but received input with shape [None, 30, 30, 4]\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "<class 'PIL.PngImagePlugin.PngImageFile'>\n",
      "(1, 30, 30, 3)\n",
      "<class 'numpy.ndarray'>\n",
      "Interdiction de circuler pour les véhicules de plus de 3,5 tonnes\n",
      "<class 'PIL.PngImagePlugin.PngImageFile'>\n",
      "(1, 30, 30, 3)\n",
      "<class 'numpy.ndarray'>\n",
      "Route glissante\n",
      "<class 'PIL.PngImagePlugin.PngImageFile'>\n",
      "(1, 30, 30, 3)\n",
      "<class 'numpy.ndarray'>\n",
      "Tout droit uniquement\n",
      "<class 'PIL.PngImagePlugin.PngImageFile'>\n",
      "(1, 30, 30, 4)\n",
      "<class 'numpy.ndarray'>\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-7-3e160a2dc0ba>\", line 90, in <lambda>\n",
      "    classify_b=Button(top,text=\"Classier l'image\",command=lambda: classify(file_path),padx=10,pady=5)\n",
      "  File \"<ipython-input-7-3e160a2dc0ba>\", line 83, in classify\n",
      "    pred = model.predict_classes([image])[0]\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\util\\deprecation.py\", line 324, in new_func\n",
      "    return func(*args, **kwargs)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\sequential.py\", line 453, in predict_classes\n",
      "    proba = self.predict(x, batch_size=batch_size, verbose=verbose)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\training.py\", line 130, in _method_wrapper\n",
      "    return method(self, *args, **kwargs)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\training.py\", line 1599, in predict\n",
      "    tmp_batch_outputs = predict_function(iterator)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 780, in __call__\n",
      "    result = self._call(*args, **kwds)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 814, in _call\n",
      "    results = self._stateful_fn(*args, **kwds)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 2829, in __call__\n",
      "    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 1843, in _filtered_call\n",
      "    return self._call_flat(\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 1923, in _call_flat\n",
      "    return self._build_call_outputs(self._inference_function.call(\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 545, in call\n",
      "    outputs = execute.execute(\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\execute.py\", line 59, in quick_execute\n",
      "    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,\n",
      "tensorflow.python.framework.errors_impl.InvalidArgumentError:  input depth must be evenly divisible by filter depth: 4 vs 3\n",
      "\t [[node sequential_1/conv2d_1/Relu (defined at <ipython-input-7-3e160a2dc0ba>:83) ]] [Op:__inference_predict_function_3018]\n",
      "\n",
      "Function call stack:\n",
      "predict_function\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "(1, 30, 30, 4)\n",
      "<class 'numpy.ndarray'>\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-7-3e160a2dc0ba>\", line 90, in <lambda>\n",
      "    classify_b=Button(top,text=\"Classier l'image\",command=lambda: classify(file_path),padx=10,pady=5)\n",
      "  File \"<ipython-input-7-3e160a2dc0ba>\", line 83, in classify\n",
      "    pred = model.predict_classes([image])[0]\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\util\\deprecation.py\", line 324, in new_func\n",
      "    return func(*args, **kwargs)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\sequential.py\", line 453, in predict_classes\n",
      "    proba = self.predict(x, batch_size=batch_size, verbose=verbose)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\training.py\", line 130, in _method_wrapper\n",
      "    return method(self, *args, **kwargs)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\training.py\", line 1599, in predict\n",
      "    tmp_batch_outputs = predict_function(iterator)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 780, in __call__\n",
      "    result = self._call(*args, **kwds)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 814, in _call\n",
      "    results = self._stateful_fn(*args, **kwds)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 2829, in __call__\n",
      "    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 1843, in _filtered_call\n",
      "    return self._call_flat(\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 1923, in _call_flat\n",
      "    return self._build_call_outputs(self._inference_function.call(\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 545, in call\n",
      "    outputs = execute.execute(\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\execute.py\", line 59, in quick_execute\n",
      "    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,\n",
      "tensorflow.python.framework.errors_impl.InvalidArgumentError:  input depth must be evenly divisible by filter depth: 4 vs 3\n",
      "\t [[node sequential_1/conv2d_1/Relu (defined at <ipython-input-7-3e160a2dc0ba>:83) ]] [Op:__inference_predict_function_3018]\n",
      "\n",
      "Function call stack:\n",
      "predict_function\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "(1, 30, 30, 4)\n",
      "<class 'numpy.ndarray'>\n",
      "(1, 30, 30, 4)\n",
      "<class 'numpy.ndarray'>\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-7-3e160a2dc0ba>\", line 90, in <lambda>\n",
      "    classify_b=Button(top,text=\"Classier l'image\",command=lambda: classify(file_path),padx=10,pady=5)\n",
      "  File \"<ipython-input-7-3e160a2dc0ba>\", line 83, in classify\n",
      "    pred = model.predict_classes([image])[0]\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\util\\deprecation.py\", line 324, in new_func\n",
      "    return func(*args, **kwargs)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\sequential.py\", line 453, in predict_classes\n",
      "    proba = self.predict(x, batch_size=batch_size, verbose=verbose)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\training.py\", line 130, in _method_wrapper\n",
      "    return method(self, *args, **kwargs)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\training.py\", line 1599, in predict\n",
      "    tmp_batch_outputs = predict_function(iterator)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 780, in __call__\n",
      "    result = self._call(*args, **kwds)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 814, in _call\n",
      "    results = self._stateful_fn(*args, **kwds)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 2829, in __call__\n",
      "    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 1843, in _filtered_call\n",
      "    return self._call_flat(\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 1923, in _call_flat\n",
      "    return self._build_call_outputs(self._inference_function.call(\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 545, in call\n",
      "    outputs = execute.execute(\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\execute.py\", line 59, in quick_execute\n",
      "    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,\n",
      "tensorflow.python.framework.errors_impl.InvalidArgumentError:  input depth must be evenly divisible by filter depth: 4 vs 3\n",
      "\t [[node sequential_1/conv2d_1/Relu (defined at <ipython-input-7-3e160a2dc0ba>:83) ]] [Op:__inference_predict_function_3018]\n",
      "\n",
      "Function call stack:\n",
      "predict_function\n",
      "\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-7-3e160a2dc0ba>\", line 90, in <lambda>\n",
      "    classify_b=Button(top,text=\"Classier l'image\",command=lambda: classify(file_path),padx=10,pady=5)\n",
      "  File \"<ipython-input-7-3e160a2dc0ba>\", line 83, in classify\n",
      "    pred = model.predict_classes([image])[0]\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\util\\deprecation.py\", line 324, in new_func\n",
      "    return func(*args, **kwargs)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\sequential.py\", line 453, in predict_classes\n",
      "    proba = self.predict(x, batch_size=batch_size, verbose=verbose)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\training.py\", line 130, in _method_wrapper\n",
      "    return method(self, *args, **kwargs)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\training.py\", line 1599, in predict\n",
      "    tmp_batch_outputs = predict_function(iterator)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 780, in __call__\n",
      "    result = self._call(*args, **kwds)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 814, in _call\n",
      "    results = self._stateful_fn(*args, **kwds)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 2829, in __call__\n",
      "    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 1843, in _filtered_call\n",
      "    return self._call_flat(\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 1923, in _call_flat\n",
      "    return self._build_call_outputs(self._inference_function.call(\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 545, in call\n",
      "    outputs = execute.execute(\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\execute.py\", line 59, in quick_execute\n",
      "    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,\n",
      "tensorflow.python.framework.errors_impl.InvalidArgumentError:  input depth must be evenly divisible by filter depth: 4 vs 3\n",
      "\t [[node sequential_1/conv2d_1/Relu (defined at <ipython-input-7-3e160a2dc0ba>:83) ]] [Op:__inference_predict_function_3018]\n",
      "\n",
      "Function call stack:\n",
      "predict_function\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "<class 'PIL.JpegImagePlugin.JpegImageFile'>\n",
      "(1, 30, 30, 3)\n",
      "<class 'numpy.ndarray'>\n",
      "Travaux\n",
      "<class 'PIL.JpegImagePlugin.JpegImageFile'>\n",
      "(1, 30, 30, 3)\n",
      "<class 'numpy.ndarray'>\n",
      "Passage d'enfants\n",
      "<class 'PIL.JpegImagePlugin.JpegImageFile'>\n",
      "(1, 30, 30, 3)\n",
      "<class 'numpy.ndarray'>\n",
      "Limite de vitesse (30 km/h)\n",
      "<class 'PIL.JpegImagePlugin.JpegImageFile'>\n",
      "(1, 30, 30, 3)\n",
      "<class 'numpy.ndarray'>\n",
      "Limite de vitesse (50 km/h)\n",
      "<class 'PIL.JpegImagePlugin.JpegImageFile'>\n",
      "(1, 30, 30, 3)\n",
      "<class 'numpy.ndarray'>\n",
      "Route glissante\n",
      "<class 'PIL.JpegImagePlugin.JpegImageFile'>\n",
      "(1, 30, 30, 3)\n",
      "<class 'numpy.ndarray'>\n",
      "Passage d'enfants\n",
      "<class 'PIL.JpegImagePlugin.JpegImageFile'>\n",
      "<class 'PIL.JpegImagePlugin.JpegImageFile'>\n",
      "(1, 30, 30, 3)\n",
      "<class 'numpy.ndarray'>\n",
      "Travaux\n",
      "<class 'PIL.PngImagePlugin.PngImageFile'>\n",
      "(1, 30, 30, 4)\n",
      "<class 'numpy.ndarray'>\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-7-3e160a2dc0ba>\", line 90, in <lambda>\n",
      "    classify_b=Button(top,text=\"Classier l'image\",command=lambda: classify(file_path),padx=10,pady=5)\n",
      "  File \"<ipython-input-7-3e160a2dc0ba>\", line 83, in classify\n",
      "    pred = model.predict_classes([image])[0]\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\util\\deprecation.py\", line 324, in new_func\n",
      "    return func(*args, **kwargs)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\sequential.py\", line 453, in predict_classes\n",
      "    proba = self.predict(x, batch_size=batch_size, verbose=verbose)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\training.py\", line 130, in _method_wrapper\n",
      "    return method(self, *args, **kwargs)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\training.py\", line 1599, in predict\n",
      "    tmp_batch_outputs = predict_function(iterator)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 780, in __call__\n",
      "    result = self._call(*args, **kwds)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 814, in _call\n",
      "    results = self._stateful_fn(*args, **kwds)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 2829, in __call__\n",
      "    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 1843, in _filtered_call\n",
      "    return self._call_flat(\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 1923, in _call_flat\n",
      "    return self._build_call_outputs(self._inference_function.call(\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 545, in call\n",
      "    outputs = execute.execute(\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\execute.py\", line 59, in quick_execute\n",
      "    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,\n",
      "tensorflow.python.framework.errors_impl.InvalidArgumentError:  input depth must be evenly divisible by filter depth: 4 vs 3\n",
      "\t [[node sequential_1/conv2d_1/Relu (defined at <ipython-input-7-3e160a2dc0ba>:83) ]] [Op:__inference_predict_function_3018]\n",
      "\n",
      "Function call stack:\n",
      "predict_function\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "(1, 30, 30, 4)\n",
      "<class 'numpy.ndarray'>\n",
      "(1, 30, 30, 4)\n",
      "<class 'numpy.ndarray'>\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-7-3e160a2dc0ba>\", line 90, in <lambda>\n",
      "    classify_b=Button(top,text=\"Classier l'image\",command=lambda: classify(file_path),padx=10,pady=5)\n",
      "  File \"<ipython-input-7-3e160a2dc0ba>\", line 83, in classify\n",
      "    pred = model.predict_classes([image])[0]\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\util\\deprecation.py\", line 324, in new_func\n",
      "    return func(*args, **kwargs)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\sequential.py\", line 453, in predict_classes\n",
      "    proba = self.predict(x, batch_size=batch_size, verbose=verbose)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\training.py\", line 130, in _method_wrapper\n",
      "    return method(self, *args, **kwargs)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\training.py\", line 1599, in predict\n",
      "    tmp_batch_outputs = predict_function(iterator)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 780, in __call__\n",
      "    result = self._call(*args, **kwds)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 814, in _call\n",
      "    results = self._stateful_fn(*args, **kwds)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 2829, in __call__\n",
      "    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 1843, in _filtered_call\n",
      "    return self._call_flat(\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 1923, in _call_flat\n",
      "    return self._build_call_outputs(self._inference_function.call(\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 545, in call\n",
      "    outputs = execute.execute(\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\execute.py\", line 59, in quick_execute\n",
      "    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,\n",
      "tensorflow.python.framework.errors_impl.InvalidArgumentError:  input depth must be evenly divisible by filter depth: 4 vs 3\n",
      "\t [[node sequential_1/conv2d_1/Relu (defined at <ipython-input-7-3e160a2dc0ba>:83) ]] [Op:__inference_predict_function_3018]\n",
      "\n",
      "Function call stack:\n",
      "predict_function\n",
      "\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-7-3e160a2dc0ba>\", line 90, in <lambda>\n",
      "    classify_b=Button(top,text=\"Classier l'image\",command=lambda: classify(file_path),padx=10,pady=5)\n",
      "  File \"<ipython-input-7-3e160a2dc0ba>\", line 83, in classify\n",
      "    pred = model.predict_classes([image])[0]\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\util\\deprecation.py\", line 324, in new_func\n",
      "    return func(*args, **kwargs)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\sequential.py\", line 453, in predict_classes\n",
      "    proba = self.predict(x, batch_size=batch_size, verbose=verbose)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\training.py\", line 130, in _method_wrapper\n",
      "    return method(self, *args, **kwargs)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\training.py\", line 1599, in predict\n",
      "    tmp_batch_outputs = predict_function(iterator)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 780, in __call__\n",
      "    result = self._call(*args, **kwds)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 814, in _call\n",
      "    results = self._stateful_fn(*args, **kwds)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 2829, in __call__\n",
      "    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 1843, in _filtered_call\n",
      "    return self._call_flat(\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 1923, in _call_flat\n",
      "    return self._build_call_outputs(self._inference_function.call(\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 545, in call\n",
      "    outputs = execute.execute(\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\execute.py\", line 59, in quick_execute\n",
      "    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,\n",
      "tensorflow.python.framework.errors_impl.InvalidArgumentError:  input depth must be evenly divisible by filter depth: 4 vs 3\n",
      "\t [[node sequential_1/conv2d_1/Relu (defined at <ipython-input-7-3e160a2dc0ba>:83) ]] [Op:__inference_predict_function_3018]\n",
      "\n",
      "Function call stack:\n",
      "predict_function\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "(1, 30, 30, 4)\n",
      "<class 'numpy.ndarray'>\n",
      "(1, 30, 30, 4)\n",
      "<class 'numpy.ndarray'>\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-7-3e160a2dc0ba>\", line 90, in <lambda>\n",
      "    classify_b=Button(top,text=\"Classier l'image\",command=lambda: classify(file_path),padx=10,pady=5)\n",
      "  File \"<ipython-input-7-3e160a2dc0ba>\", line 83, in classify\n",
      "    pred = model.predict_classes([image])[0]\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\util\\deprecation.py\", line 324, in new_func\n",
      "    return func(*args, **kwargs)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\sequential.py\", line 453, in predict_classes\n",
      "    proba = self.predict(x, batch_size=batch_size, verbose=verbose)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\training.py\", line 130, in _method_wrapper\n",
      "    return method(self, *args, **kwargs)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\training.py\", line 1599, in predict\n",
      "    tmp_batch_outputs = predict_function(iterator)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 780, in __call__\n",
      "    result = self._call(*args, **kwds)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 814, in _call\n",
      "    results = self._stateful_fn(*args, **kwds)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 2829, in __call__\n",
      "    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 1843, in _filtered_call\n",
      "    return self._call_flat(\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 1923, in _call_flat\n",
      "    return self._build_call_outputs(self._inference_function.call(\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 545, in call\n",
      "    outputs = execute.execute(\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\execute.py\", line 59, in quick_execute\n",
      "    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,\n",
      "tensorflow.python.framework.errors_impl.InvalidArgumentError:  input depth must be evenly divisible by filter depth: 4 vs 3\n",
      "\t [[node sequential_1/conv2d_1/Relu (defined at <ipython-input-7-3e160a2dc0ba>:83) ]] [Op:__inference_predict_function_3018]\n",
      "\n",
      "Function call stack:\n",
      "predict_function\n",
      "\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-7-3e160a2dc0ba>\", line 90, in <lambda>\n",
      "    classify_b=Button(top,text=\"Classier l'image\",command=lambda: classify(file_path),padx=10,pady=5)\n",
      "  File \"<ipython-input-7-3e160a2dc0ba>\", line 83, in classify\n",
      "    pred = model.predict_classes([image])[0]\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\util\\deprecation.py\", line 324, in new_func\n",
      "    return func(*args, **kwargs)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\sequential.py\", line 453, in predict_classes\n",
      "    proba = self.predict(x, batch_size=batch_size, verbose=verbose)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\training.py\", line 130, in _method_wrapper\n",
      "    return method(self, *args, **kwargs)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\training.py\", line 1599, in predict\n",
      "    tmp_batch_outputs = predict_function(iterator)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 780, in __call__\n",
      "    result = self._call(*args, **kwds)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 814, in _call\n",
      "    results = self._stateful_fn(*args, **kwds)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 2829, in __call__\n",
      "    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 1843, in _filtered_call\n",
      "    return self._call_flat(\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 1923, in _call_flat\n",
      "    return self._build_call_outputs(self._inference_function.call(\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 545, in call\n",
      "    outputs = execute.execute(\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\execute.py\", line 59, in quick_execute\n",
      "    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,\n",
      "tensorflow.python.framework.errors_impl.InvalidArgumentError:  input depth must be evenly divisible by filter depth: 4 vs 3\n",
      "\t [[node sequential_1/conv2d_1/Relu (defined at <ipython-input-7-3e160a2dc0ba>:83) ]] [Op:__inference_predict_function_3018]\n",
      "\n",
      "Function call stack:\n",
      "predict_function\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "(1, 30, 30, 4)\n",
      "<class 'numpy.ndarray'>\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-7-3e160a2dc0ba>\", line 90, in <lambda>\n",
      "    classify_b=Button(top,text=\"Classier l'image\",command=lambda: classify(file_path),padx=10,pady=5)\n",
      "  File \"<ipython-input-7-3e160a2dc0ba>\", line 83, in classify\n",
      "    pred = model.predict_classes([image])[0]\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\util\\deprecation.py\", line 324, in new_func\n",
      "    return func(*args, **kwargs)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\sequential.py\", line 453, in predict_classes\n",
      "    proba = self.predict(x, batch_size=batch_size, verbose=verbose)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\training.py\", line 130, in _method_wrapper\n",
      "    return method(self, *args, **kwargs)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\training.py\", line 1599, in predict\n",
      "    tmp_batch_outputs = predict_function(iterator)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 780, in __call__\n",
      "    result = self._call(*args, **kwds)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 814, in _call\n",
      "    results = self._stateful_fn(*args, **kwds)\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 2829, in __call__\n",
      "    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 1843, in _filtered_call\n",
      "    return self._call_flat(\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 1923, in _call_flat\n",
      "    return self._build_call_outputs(self._inference_function.call(\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 545, in call\n",
      "    outputs = execute.execute(\n",
      "  File \"c:\\Users\\sabri\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\execute.py\", line 59, in quick_execute\n",
      "    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,\n",
      "tensorflow.python.framework.errors_impl.InvalidArgumentError:  input depth must be evenly divisible by filter depth: 4 vs 3\n",
      "\t [[node sequential_1/conv2d_1/Relu (defined at <ipython-input-7-3e160a2dc0ba>:83) ]] [Op:__inference_predict_function_3018]\n",
      "\n",
      "Function call stack:\n",
      "predict_function\n",
      "\n"
     ]
    }
   ],
   "source": [
    "import tkinter as tk\n",
    "from tkinter import filedialog\n",
    "from tkinter import *\n",
    "from PIL import ImageTk, Image\n",
    "\n",
    "import numpy as np \n",
    "import pandas as pd \n",
    "import tensorflow as tf\n",
    "from PIL import Image\n",
    "import os\n",
    "from keras.utils import to_categorical\n",
    "from keras.models import Sequential, load_model\n",
    "from keras.layers import Conv2D, MaxPool2D, Dense, Flatten, Dropout\n",
    "import numpy\n",
    "\n",
    "#load the trained model to classify sign\n",
    "from keras.models import load_model\n",
    "model = load_model('traffic_classifier.h5')\n",
    "\n",
    "#dictionary to label all traffic signs class.\n",
    "classes = { 1 : \"Limite de vitesse (20 km/h)\",\n",
    "            2 : \"Limite de vitesse (30 km/h)\",\n",
    "            3 : \"Limite de vitesse (50 km/h)\",\n",
    "            4 : \"Limite de vitesse (60 km/h)\",\n",
    "            5 : \"Limite de vitesse (70 km/h)\",\n",
    "            6 : \"Limite de vitesse (80 km/h)\",\n",
    "            7 : \"Fin de limite de vitesse (80 km/h)\",\n",
    "            8 : \"Limite de vitesse (100 km/h)\",\n",
    "            9 : \"Limite de vitesse (120 km/h)\",\n",
    "            10 : \"Interdiction de dépasser\",\n",
    "            11 : \"Interdiction de dépasser les véhicules de plus de 3,5 tonnes\",\n",
    "            12 : \"Priorité à droite à une intersection\",\n",
    "            13 : \"Route prioritaire\",\n",
    "            14 : \"Cédez le passage\",\n",
    "            15 : \"Stop\",\n",
    "            16 : \"Interdiction de circuler\",\n",
    "            17 : \"Interdiction de circuler pour les véhicules de plus de 3,5 tonnes\",\n",
    "            18 : \"Interdiction d'entrer\",\n",
    "            19 : \"Danger\",\n",
    "            20 : \"Virage dangereux à gauche\",\n",
    "            21 : \"Virage dangereux à droite\",\n",
    "            22 : \"Double virage\",\n",
    "            23 : \"Route bosselée\",\n",
    "            24 : \"Route glissante\",\n",
    "            25 : \"Rétrécissement de la chaussée à droite\",\n",
    "            26 : \"Travaux\",\n",
    "            27 : \"Feux de signalisation\",\n",
    "            28 : \"Passage piéton\",\n",
    "            29 : \"Passage d'enfants\",\n",
    "            30 : \"Passage de cyclistes\",\n",
    "            31 : \"Attention verglas/neige\",\n",
    "            32 : \"Passage d'animaux sauvages\",\n",
    "            33 : \"Fin de limitation de vitesse et d'interdiction de dépasser\",\n",
    "            34 : \"Tourner à droite\",\n",
    "            35 : \"Tourner à gauche\",\n",
    "            36 : \"Tout droit uniquement\",\n",
    "            37 : \"Tout droit ou à droite\",\n",
    "            38 : \"Tout droit ou à gauche\",\n",
    "            39 : \"Obligation de tourner à droite\",\n",
    "            40 : \"Obligation de tourner à gauche\",\n",
    "            41 : \"Rond-point obligatoire\",\n",
    "            42 : \"Fin de l'interdiction de dépasser\",\n",
    "            43 : \"Fin de l'interdiction de dépasser les véhicules de plus de 3,5 tonnes\" }\n",
    "                 \n",
    "#initialise GUI\n",
    "top=tk.Tk()\n",
    "top.geometry('1000x600')\n",
    "top.title('Reconnaissance des panneaux de signalisation')\n",
    "top.configure(background='#CDCDCD')\n",
    "\n",
    "label=Label(top,background='#CDCDCD', font=('arial',15,'bold'))\n",
    "sign_image = Label(top)\n",
    "\n",
    "def classify(file_path):\n",
    "    global label_packed\n",
    "    image = Image.open(file_path)    \n",
    "    image = image.resize((30,30))\n",
    "    image = numpy.expand_dims(image, axis=0)\n",
    "    image = numpy.array(image)\n",
    "    \n",
    "    print(image.shape)\n",
    "    print(type(image))\n",
    "    pred = model.predict_classes([image])[0]\n",
    "    sign = classes[pred+1]\n",
    "    print(sign)\n",
    "    label.configure(foreground='#011638', text=sign) \n",
    "   \n",
    "\n",
    "def show_classify_button(file_path):\n",
    "    classify_b=Button(top,text=\"Classier l'image\",command=lambda: classify(file_path),padx=10,pady=5)\n",
    "    classify_b.configure(background='#364156', foreground='white',font=('arial',10,'bold'))\n",
    "    #classify_b.pack(side=BOTTOM,pady=20)\n",
    "    classify_b.place(relx=0.79,rely=0.46)\n",
    "\n",
    "def upload_image():\n",
    "    try:\n",
    "        file_path=filedialog.askopenfilename()\n",
    "        uploaded=Image.open(file_path)\n",
    "        uploaded.thumbnail(((top.winfo_width()/2.25),(top.winfo_height()/2.25)))\n",
    "        im=ImageTk.PhotoImage(uploaded)\n",
    "        \n",
    "        sign_image.configure(image=im)\n",
    "        sign_image.image=im\n",
    "        label.configure(text='')\n",
    "        print(type(uploaded))\n",
    "        show_classify_button(file_path)\n",
    "    except:\n",
    "        pass\n",
    "\n",
    "upload=Button(top,text=\"Importer image\",command=upload_image,padx=10,pady=5)\n",
    "upload.configure(background='#364156', foreground='white',font=('arial',10,'bold'))\n",
    "\n",
    "upload.pack(side=BOTTOM,pady=50)\n",
    "sign_image.pack(side=BOTTOM,expand=True)\n",
    "label.pack(side=BOTTOM,expand=True)\n",
    "heading = Label(top, text=\"Reconnaissance des panneaux de signalisation par DeepLearning\",pady=20, font=('arial',20,'bold'))\n",
    "heading.configure(background='#CDCDCD',foreground='#364156')\n",
    "heading.pack()\n",
    "top.mainloop()\n",
    "\n"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "type()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "base",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.8"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
